compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

npmScopes:
  react-native-google-signin:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "${NPM_TOKEN_GOOGLE_SIGN_IN}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs
