/* do not change this file, it is auto generated by storybook. */

import {
  start,
  prepareStories,
  getProjectAnnotations,
} from "@storybook/react-native";

import "/home/samkach/clixpesa/node_modules/@storybook/addon-ondevice-controls/register";
import "/home/samkach/clixpesa/node_modules/@chromatic-com/storybook/register";
import "@storybook/addon-webpack5-compiler-swc/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../../packages/ui",
    files: "**/*.@(mdx|stories.@(ts|tsx))",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.(mdx|stories\.(ts|tsx)))$/,
    // @ts-ignore
    req: require.context(
      "../../../packages/ui",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.(mdx|stories\.(ts|tsx)))$/
    ),
  },
];

declare global {
  var view: ReturnType<typeof start>;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require("./preview"),
  require("@storybook/react-native/dist/preview"),
];

global.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  const { importMap } = prepareStories({ storyEntries: normalizedStories });

  global.view._preview.onStoriesChanged({
    importFn: async (importPath: string) => importMap[importPath],
  });

  global.view._preview.onGetProjectAnnotationsChanged({
    getProjectAnnotations: getProjectAnnotations(global.view, annotations),
  });
}

export const view = global.view;
